Add mtbl_metadata_* functions to retrieve trailer metadata
My goal was to create an in-memory representation of the original data.  To do this, it's very helpful to know the size of the source data, namely the key & value bytes, and the number of entries.

I added the other getters so that the "mtbl_info" program wouldn't have to use private APIs to do its job.

I renamed `trailer` to `mtbl_metadata` since that's a more meaningful name for the structure. I'm happy to roll back the rename, if you're sure you like `mtbl_trailer` better.

Test Plan:

Checked that the rename is complete:

```
git grep -i trailer
find | grep -i trailer
```

Built & tested:

```
./autogen.sh && ./configure && make && make check
sudo make install
(for f in t/*.data; do /usr/bin/mtbl_info $f ; done) &> UBUNTU_SYS_OUTPUT
(for f in t/*.data; do /usr/local/bin/mtbl_info $f ; done) &> NEW_OUTPUT
diff UBUNTU_SYS_OUTPUT NEW_OUTPUT
```

The difference in error message seems acceptable:

```
1c1
< Error: lseek() failed: Invalid argument
---
> Error: mtbl_reader_init() on t/test-deb716628.data failed
```